### ISSUE TITLE
Typo in config file

### ISSUE THREAD

**Issue by jnko** [lbseale/odroid-fan#1]
I was a little bit confused why xu4fan consumes about 1.3% CPU while doing nothing special staying in python sleep() method and increased the poll_inverval value to 5. After restarting nothing happened with CPU usage. poll_interval was still 0.25 in wait() method. You may already noticed it - I took some minutes longer ;)

The config file provided by you has a simple typo in it:
...
poll_inverval = 0.25 should be corrected to poll_interval = 0.25

**Comment by lbseale** [comment]
Nice catch! I did not realize that. I'll fix it.
